#? Config file for btop v.1.4.6

color_theme = "blue-lock-facility"
theme_background = true
truecolor = true
force_tty = false
presets = "cpu:1:default,proc:0:default cpu:0:default,mem:0:default,net:0:default cpu:0:block,net:0:tty"
vim_keys = true
rounded_corners = true
terminal_sync = true
graph_symbol = "braille"
graph_symbol_cpu = "default"
graph_symbol_gpu = "default"
graph_symbol_mem = "default"
graph_symbol_net = "default"
graph_symbol_proc = "default"
shown_boxes = "cpu mem net proc"
update_ms = 2000
proc_sorting = "cpu lazy"
proc_reversed = false
proc_tree = false
proc_colors = true
proc_gradient = true
proc_per_core = false
proc_mem_bytes = true
proc_cpu_graphs = true
proc_info_smaps = false
proc_left = false
proc_filter_kernel = false
proc_aggregate = false
keep_dead_proc_usage = false
cpu_graph_upper = "Auto"
cpu_graph_lower = "Auto"
show_gpu_info = "Auto"
cpu_invert_lower = true
cpu_single_graph = false
cpu_bottom = false
