[Appearance]
color_scheme_path=
custom_palette=true
icon_theme=Papirus-Dark
style=Fusion
standard_dialogs=default

[Fonts]
fixed="JetBrains Mono Nerd Font,11,-1,5,50,0,0,0,0,0"
general="Space Grotesk,11,-1,5,50,0,0,0,0,0"
