background = #050B18
foreground = #F4F8FF
cursor-color = #65D9FF
selection-background = #123C7C
selection-foreground = #F4F8FF
font-family = JetBrains Mono Nerd Font
font-size = 13

palette = 0=#050B18
palette = 1=#FF4D4D
palette = 2=#35D07F
palette = 3=#8FD6FF
palette = 4=#197DFF
palette = 5=#7CCBFF
palette = 6=#65D9FF
palette = 7=#F4F8FF
palette = 8=#1A335D
palette = 9=#FF7777
palette = 10=#74F0A0
palette = 11=#B7ECFF
palette = 12=#4AA3FF
palette = 13=#B4E4FF
palette = 14=#A6EEFF
palette = 15=#FFFFFF

